#  Copyright 2018 Bryant Luk
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

steps:
- name: 'gcr.io/cloud-builders/wget'
  args:
    - 'https://releases.hashicorp.com/terraform/${_TERRAFORM_VERSION}/terraform_${_TERRAFORM_VERSION}_linux_amd64.zip'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/terraform:${_TERRAFORM_VERSION}'
    - '-t'
    - 'gcr.io/$PROJECT_ID/terraform'
    - '--build-arg'
    - 'TERRAFORM_VERSION=${_TERRAFORM_VERSION}'
    - '--build-arg'
    - 'TERRAFORM_VERSION_SHA256SUM=${_TERRAFORM_VERSION_SHA256SUM}'
    - '.'
substitutions:
  _TERRAFORM_VERSION: 0.11.8
  _TERRAFORM_VERSION_SHA256SUM: 84ccfb8e13b5fce63051294f787885b76a1fedef6bdbecf51c5e586c9e20c9b7

images:
  - 'gcr.io/$PROJECT_ID/terraform:latest'
  - 'gcr.io/$PROJECT_ID/terraform:$_TERRAFORM_VERSION'
