steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--file=Dockerfile-5'
    - '--tag=gcr.io/$PROJECT_ID/swift:5'
    - '.'
  id: '5'

# Test versions
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'run'
    - '--rm'
    - 'gcr.io/$PROJECT_ID/swift:5'
    - 'swift'
    - '--version'
  wait_for: ['5']

# Tag versions
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'tag'
    - 'gcr.io/$PROJECT_ID/swift:5'
    - 'gcr.io/$PROJECT_ID/swift'
  wait_for: ['5']
  id: 'latest'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'tag'
    - 'gcr.io/$PROJECT_ID/swift:5'
    - 'gcr.io/$PROJECT_ID/swift:5.0'
  wait_for: ['5']
  id: '5.0'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'tag'
    - 'gcr.io/$PROJECT_ID/swift:5'
    - 'gcr.io/$PROJECT_ID/swift:5.0.0'
  wait_for: ['5']
  id: '5.0.0'

# Test latest
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'run'
    - '--rm'
    - 'gcr.io/$PROJECT_ID/swift'
    - 'swift'
    - '--version'
  wait_for: ['latest']

images:
- 'gcr.io/$PROJECT_ID/swift:latest'
- 'gcr.io/$PROJECT_ID/swift:5'
- 'gcr.io/$PROJECT_ID/swift:5.0'
- 'gcr.io/$PROJECT_ID/swift:5.0.0'
