# Modified from:
# https://github.com/apple/swift-docker/blob/966cfdef637e319d28b681e42bdb905b070bf338/5.0/ubuntu/18.04/Dockerfile
FROM ubuntu:18.04

# Install related packages
RUN DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get -q update && \
    DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get -q install -y \
    libatomic1 \
    libbsd0 \
    libcurl4 \
    libxml2 \
    libedit2 \
    libsqlite3-0 \
    libc6-dev \
    binutils \
    libgcc-5-dev \
    libstdc++-5-dev \
    libpython2.7 \
    tzdata \
    git \
    pkg-config \
    make \
    curl \
    libicu-dev \
    libedit-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    && rm -r /var/lib/apt/lists/*

# Everything up to here should cache nicely between Swift versions, assuming dev dependencies change little
ARG SWIFT_PLATFORM=ubuntu18.04
ARG SWIFT_BRANCH=swift-5.0-release
ARG SWIFT_VERSION=swift-5.0-RELEASE

ENV SWIFT_PLATFORM=$SWIFT_PLATFORM \
    SWIFT_BRANCH=$SWIFT_BRANCH \
    SWIFT_VERSION=$SWIFT_VERSION

# Copy the GPG key signatures
# Originally from https://swift.org/keys/all-keys.asc as mentioned on https://swift.org/download/
COPY all-keys.asc /tmp/all-keys.asc

# Download Swift package, then unpack, cleanup and execute permissions for foundation libs
RUN SWIFT_URL=https://swift.org/builds/$SWIFT_BRANCH/$(echo "$SWIFT_PLATFORM" | tr -d .)/$SWIFT_VERSION/$SWIFT_VERSION-$SWIFT_PLATFORM.tar.gz \
    && curl -fSsL $SWIFT_URL -o swift.tar.gz \
    && curl -fSsL $SWIFT_URL.sig -o swift.tar.gz.sig \
    && export GNUPGHOME="$(mktemp -d)" \
    && gpg --import /tmp/all-keys.asc \
    && gpg --batch --verify --quiet swift.tar.gz.sig swift.tar.gz \
    && tar -xzf swift.tar.gz --directory / --strip-components=1 \
    && rm -r swift.tar.gz.sig swift.tar.gz \
    && rm -rf "$GNUPGHOME" || true \
    && chmod -R o+r /usr/lib/swift

# Print Installed Swift Version
RUN swift --version
